// <auto-generated />
namespace MvcDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _6_Notification_PrjectTask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6_Notification_PrjectTask));
        
        string IMigrationMetadata.Id
        {
            get { return "202006011918090_6_Notification_PrjectTask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
