// <auto-generated />
namespace MvcDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _4_ProjectTaskFKNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4_ProjectTaskFKNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202005280043296_4_ProjectTaskFKNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
